name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USER: ${{secrets.SD_USER}}
      PASSWORD: ${{secrets.SD_PASSWORD}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Edge
      uses: abhi1693/setup-browser@v0.3.4
      with:
        browser: edge
        version: latest
    - name: Run tests
      run: mvn clean test -Duser=$USER -Dpassword=$PASSWORD
    - name: Run cross browser tests
      run: mvn clean test -DsuiteXmlFile='src/test/resources/CrossBrowserTest.xml'
